apiVersion: v1
kind: ConfigMap
metadata:
  name: express-test-frontend
  namespace: express-test-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  VITE_BACKEND_URL: "https://test.ipremay.de" 
