apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-test-frontend
  namespace: express-test-frontend
  labels:
    app: express-test-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    matchLabels:
      app: express-test-frontend
  template:
    metadata:
      labels:
        app: express-test-frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: frontend
        image: marcelm119/dev-repo:express-test-frontend-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: VITE_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: express-test-frontend
              key: VITE_BACKEND_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
